export const CREATE_MODEL_REQUEST = 'CREATE_MODEL_REQUEST';
export const CREATE_MODEL_SUCCESS = 'CREATE_MODEL_SUCCESS';
export const CREATE_MODEL_FAILED = 'CREATE_MODEL_FAILED';

export const UPDATE_MODEL_REQUEST = 'UPDATE_MODEL_REQUEST'
export const UPDATE_MODEL_SUCCESS = 'UPDATE_MODEL_SUCCESS'
export const UPDATE_MODEL_FAILED = 'UPDATE_MODEL_FAILED'

export const SET_MODEL_DATA = "SET_MODEL_DATA";