export const EDIT_EXAM = "EDIT_EXAM";
export const SHOW_EXAM_EDIT_FORM = "SHOW_EXAM_EDIT_FORM";
export const SHOW_EXAM_FORM = 'SHOW_EXAM_FORM';

export const CREATE_EXAMEN_REQUEST = 'CREATE_EXAMEN_REQUEST';
export const CREATE_EXAMEN_SUCCESS = 'CREATE_EXAMEN_SUCCESS';
export const CREATE_EXAMEN_FAILURE = 'CREATE_EXAMEN_FAILURE';

export const ADD_EXAM = 'ADD_EXAM';
export const ADD_EXAM_GROUPED = 'ADD_EXAM_GROUPED';
export const CREATE_EXAMEN_GROUP = 'CREATE_EXAMEN_GROUP';
export const GET_EXAM_GROUP = 'GET_EXAM_GROUP';

export const ADD_EXAM_ON_ALL_GROUP = 'ADD_EXAM_ON_ALL_GROUP';
export const SET_ACTIVE_GROUP = 'SET_ACTIVE_GROUP';
export const NUMBER_OF_GROUPS_CHANGE = 'NUMBER_OF_GROUPS_CHANGE';
export const CREATE_GROUPS = 'CREATE_GROUPS';

export const DELETE_EXAM_GROUP = 'DELETE_EXAM_GROUP';
export const DELETE_EXAM_SIMPLE = 'DELETE_EXAM_SIMPLE';