export const EDIT_EXAM = "EDIT_EXAM";
export const SHOW_EXAM_EDIT_FORM = "SHOW_EXAM_EDIT_FORM";
export const SHOW_EXAM_FORM = "SHOW_EXAM_FORM";

export const CREATE_EXAMEN_REQUEST = "CREATE_EXAMEN_REQUEST";
export const CREATE_EXAMEN_SUCCESS = "CREATE_EXAMEN_SUCCESS";
export const CREATE_EXAMEN_FAILURE = "CREATE_EXAMEN_FAILURE";

export const ADD_EXAM = "ADD_EXAM";
export const ADD_EXAM_GROUPED = "ADD_EXAM_GROUPED";
export const CREATE_EXAMEN_GROUP = "CREATE_EXAMEN_GROUP";
export const GET_EXAM_GROUP = "GET_EXAM_GROUP";

export const ADD_EXAM_ON_ALL_GROUP = "ADD_EXAM_ON_ALL_GROUP";
export const SET_ACTIVE_GROUP = "SET_ACTIVE_GROUP";
export const NUMBER_OF_GROUPS_CHANGE = "NUMBER_OF_GROUPS_CHANGE";
export const CREATE_GROUPS = "CREATE_GROUPS";
export const SHARE_GROUP_PAYLOAD = "SHARE_GROUP_PAYLOAD";
export const UPDATE_MODELE_DATA = "UPDATE_MODELE_DATA";
export const SHARE_GROUP_EXAM_PAYLOAD = "SHARE_GROUP_EXAM_PAYLOAD";
export const SHARE_LIST_EXAMS_GROUP = "SHARE_LIST_EXAMS_GROUP";
export const NEW_EXAM = "NEW_EXAM";
export const SHARE_ALL_EXAMS = "SHARE_ALL_EXAMS";
export const EXAM_TO_EDIT = "EXAM_TO_EDIT";
export const SHARE_EXAM_DATA = "SHARE_EXAM_DATA";
export const SHARE_PRATICIEN_DATA = "SHARE_PRATICIEN_DATA";
export const SHARE_EXAM_PAYLOAD = "SHARE_EXAM_PAYLOAD";
export const SHARE_SPECIALITIE_DATA = "SHARE_SPECIALITIE_DATA";
export const SHARE_MOTIF = "SHARE_MOTIF";
export const SHARE_LIEU = "SHARE_LIEU";

export const DELETE_EXAM_GROUP = "DELETE_EXAM_GROUP";
export const DELETE_EXAM_SIMPLE = "DELETE_EXAM_SIMPLE";

export const DELETE_GROUP = "DELETE_GROUP";
export const FIX_GROUP_POSITION = "FIX_GROUP_POSITION";
export const FIX_EXAMEN_POSITION = "FIX_EXAMEN_POSITION";

export const SET_ESPACEMENT = 'SET_ESPACEMENT';
export const SET_ESPACEMENT_NON_GROUPE = 'SET_ESPACEMENT_NON_GROUPE';
export const CREATE_ESPACEMENTS = 'CREATE_ESPACEMENTS';
export const CREATE_ESPACEMENTS_NON_GROUPE = 'CREATE_ESPACEMENTS_NON_GROUPE;'
export const SET_ACTUAL_NON_GROUPE_INDEX = 'SET_ACTUAL_NON_GROUPE_INDEX';
export const SET_ESPACEMENT_SUB_EXAM = 'SET_ESPACEMENT_SUB_EXAM';
export const CREATE_ESPACEMENTS_SUB_EXAM = 'CREATE_ESPACEMENTS_SUB_EXAM';
export const TOGGLE_FIXE_EXAM_POSITION = 'FIXE_EXAM_POSITION';
export const TOGGLE_FIXE_GROUP_POSITION = 'TOGGLE_FIXE_GROUP_POSITION';
export const SET_IS_CLOSE = "SET_IS_CLOSE";
export const DRAG_AND_DROP = "DRAG_AND_DROP";
export const SHOW_GROUPE_CONTENT = "SHOW_GROUPE_CONTENT" 
export const LINK_TO_EXAM = "LINK_TO_EXAM";
export const STORE_EXAMS = "STORE_EXAMS";
export const LINK_TO_GROUPE = "LINK_TO_GROUPE";
export const SET_EXAM_FORM_EDITABLE = "SET_EXAM_FORM_EDITABLE";
export const EDIT_EXAM_GROUP = "EDIT_EXAM_GROUP";
export const GET_GROUP_TO_EDITE_EXAM = "GET_GROUP_TO_EDITE_EXAM";