export const EDIT_EXAM = "EDIT_EXAM";
export const SHOW_EXAM_EDIT_FORM = "SHOW_EXAM_EDIT_FORM";
export const SHOW_EXAM_FORM = 'SHOW_EXAM_FORM';

export const CREATE_EXAMEN_REQUEST = 'CREATE_EXAMEN_REQUEST';
export const CREATE_EXAMEN_SUCCESS = 'CREATE_EXAMEN_SUCCESS';
export const CREATE_EXAMEN_FAILURE = 'CREATE_EXAMEN_FAILURE';

export const ADD_EXAM = 'ADD_EXAM';